# Generated by Django 3.0.2 on 2020-03-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Model',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=30)),
                ('u_gender', models.CharField(max_length=20)),
                ('u_address', models.CharField(max_length=200)),
                ('u_mobile', models.IntegerField(unique=True)),
                ('u_email', models.EmailField(max_length=30, unique=True)),
                ('u_password', models.CharField(max_length=30)),
            ],
        ),
    ]
