# Generated by Django 3.0.2 on 2020-03-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager_Model',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=10)),
                ('expireance', models.IntegerField(max_length=2)),
                ('Mobile', models.IntegerField(max_length=15, unique=True)),
                ('Address', models.TextField(max_length=200)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=8)),
                ('pic', models.ImageField(upload_to='admin_images/')),
            ],
        ),
    ]
