# Generated by Django 3.1.2 on 2021-03-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager_model',
            name='Mobile',
            field=models.IntegerField(unique=True),
        ),
    ]
