# Generated by Django 3.1.2 on 2021-03-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0002_auto_20210307_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager_model',
            name='expireance',
            field=models.IntegerField(),
        ),
    ]
