# Generated by Django 3.0.2 on 2020-03-13 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Model',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_model', models.CharField(max_length=30, unique=True)),
                ('c_name', models.CharField(max_length=30)),
                ('c_milege', models.IntegerField()),
                ('c_advance', models.FloatField()),
                ('c_rent_price', models.FloatField()),
                ('c_day_price', models.FloatField()),
                ('c_image', models.ImageField(upload_to='cars_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Driver_Model',
            fields=[
                ('d_id', models.IntegerField(unique=True)),
                ('d_name', models.CharField(max_length=30)),
                ('d_licence', models.CharField(max_length=30, unique=True)),
                ('d_age', models.IntegerField()),
                ('d_gender', models.CharField(max_length=20)),
                ('d_expireance', models.IntegerField()),
                ('d_mobile', models.IntegerField(primary_key=True, serialize=False)),
                ('d_email', models.EmailField(max_length=40, unique=True)),
                ('d_address', models.CharField(max_length=100)),
                ('d_image', models.ImageField(upload_to='driver_images/')),
                ('d_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager_app.Car_Model')),
            ],
        ),
    ]
