# Generated by Django 3.0.2 on 2020-03-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver_model',
            name='d_car',
        ),
        migrations.AddField(
            model_name='driver_model',
            name='d_car',
            field=models.ManyToManyField(to='Manager_app.Car_Model'),
        ),
    ]
